name: Deploy to Staging

name: Deploy to Staging

on:
  push:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build

  test:

    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Run Tests
        run: npm test
  test:

    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Run Tests
        run: npm test

  deploy-staging:

    runs-on: ubuntu-latest
    needs: [build, test]
    steps:

      - name: Deploy to Staging
        env:
          SECRET_KEY_4: ${{ secrets.SECRET_KEY_4 }}
        run: |
          echo "Deploying to Staging..."
  deploy-staging:

    runs-on: ubuntu-latest
    needs: [build, test]
    steps:

      - name: Deploy to Staging
        env:
          SECRET_KEY_4: ${{ secrets.SECRET_KEY_4 }}
        run: |
          echo "Deploying to Staging..."
