name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        env:
          MY_SECRET_NAME_EX4: ${{ secrets.MY_SECRET_NAME_EX4 }}
